from typing import Optional, Protocol

from backend.src.domain.entities.refresh_token import RefreshToken
from backend.src.domain.entities.user import User


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def save(self, user: User) -> User: ...


class RefreshTokenRepository(Protocol):
    def get_by_hash(self, token_hash: str) -> Optional[RefreshToken]: ...
    def save(self, token: RefreshToken) -> RefreshToken: ...
