from typing import Protocol, Optional, List

from backend.src.domain.entities.user import User
from backend.src.domain.entities.refresh_token import RefreshToken
from backend.src.domain.entities.workout_session import WorkoutSession
from backend.src.domain.entities.exercise_definition import ExerciseDefinition


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def save(self, user: User) -> User: ...


class RefreshTokenRepository(Protocol):
    def get_by_hash(self, token_hash: str) -> Optional[RefreshToken]: ...
    def save(self, token: RefreshToken) -> RefreshToken: ...
    def revoke_all_for_user(self, user_id: int) -> None: ...


class WorkoutSessionRepository(Protocol):
    def get_by_id(self, session_id: int) -> Optional[WorkoutSession]: ...
    def list_for_user(self, user_id: int) -> List[WorkoutSession]: ...
    def save(self, session: WorkoutSession) -> WorkoutSession: ...


class ExerciseCatalogRepository(Protocol):
    def get_by_id(self, definition_id: int) -> Optional[ExerciseDefinition]: ...
    def list_all(self) -> List[ExerciseDefinition]: ...
